[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000_000
solc = "0.8.25"
verbosity = 3

[profile.ci]
fuzz = { runs = 5000 }
invariant = { runs = 1000 }
verbosity = 4

[profile.local]
  fuzz = { runs = 50 }
  invariant = { runs = 10 }
  # Speed up compilation and tests during development.
  optimizer = true

[rpc_endpoints]
mainnet = "${ETHEREUM_NODE_MAINNET}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
