[profile.default]
evm_version = 'shanghai'
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.23"

remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "@tokenized-strategy/=lib/tokenized-strategy/src/",
    "@periphery/=lib/tokenized-strategy-periphery/src/",
    "@yearn-vaults/=lib/yearn-vaults-v3/contracts",
    "vault-periphery/=lib/vault-periphery/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config